# Generated by Django 5.0 on 2024-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_product_qty_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=9000, null=True, verbose_name='Описание'),
        ),
    ]
